### PR TITLE
Fix half opening command in web interface

### PR DESCRIPTION
**Pull request by 14yannick**
Hi,

Thanks for your work on this topic. I have already the code in use and it works very well.

I just have see a small bug in the web-interface for the half opening command.

Btw I m working on a PCB to fit all component on pinheaders. I will commit it my repo as soon it works

Best regards

### CODE REVIEW

**Review by Gifford47 — APPROVED** [review]
all is fine, thanks for your commit!
currently i`m trying to add also a pir motion sensor. therefore there is a need for one more gpio. could you plan it in your schematic please? that would be awesome!

**Comment by 14yannick** [comment]
Hi, ok I will add it in next revision. I'm also planning to make the board compatible with a 30pin dev board (actually 38). I will also add another connector for a proximity sensor to know if a car is parked below. I'm thinking also about doing some basic translation functionality.

**Comment by Gifford47** [comment]
Hi! That sounds interesting! Especially the proximity sensor could be a great feature.
Do you currently have I public repo (or a discord channel) where I could contribute to?if you already have a first pcb version I would discard my own and switch to yours.

**Comment by 14yannick** [comment]
Hi,

I haven't started the dev yet. I'm on holiday so I just launched the pcb production before leaving to have it when I back. 
I just uploaded all I have in my repo. https://github.com/14yannick/HCPBridgeMqtt/tree/development/PCB
For the dev your help will be appreciated. I think I will be able to implement the translation and the Logic for the proximity sensor. But i will probably struggle with the mqtt part.

**Comment by 14yannick** [comment]
Just saw that this board looks so much better
https://community.home-assistant.io/t/hormann-garage-door-via-mqtt/279938/168

**Comment by fisch55** [comment]
This board works like a Charme!!!!

**Comment by Gifford47** [comment]
Ok, thanks for the Info!
If we want to combine this source code with all its features with the board, we need to get the JSON PCB files from easyeda (I think it is easyeda, isn't it?)
Does anybody have it?

**Comment by 14yannick** [comment]
Json file is there

**Comment by Gifford47** [comment]
Great!
Personally I would use an ultrasonic sensor as a proximity sensor because of the distance range . Like a hc-sr04.
And a hc-sr501 motion sensor for triggering activities in a specific area underneath the supramatic.

**Comment by 14yannick** [comment]
Hi I just pushed the Integration of the hc-sr04 to my dev Repo. Do you have a discord or a place we can discuss about futur development?

**Comment by Gifford47** [comment]
Hey! No, only on GitHub. Create a new discussion here. That's the best address :)

**Pull request merged**
