### PR TITLE
Redesign Preferences

### PR DESCRIPTION
**Pull request by 14yannick**
@Tysonpower have a look it's still work in progress

### CODE REVIEW

**Comment by Tysonpower** [comment]
Looks nice! I can't do any Tests until September due to my Vacation but if it still works with the webUI this should be a nice redesign for sure so far :)

**Comment by Tysonpower** [comment]
Did you do any Tests on this so far?

**Comment by 14yannick** [comment]
It's still work in progress but I think I will commit my additional changes asap and then run a build on my door for a couple of days to check. I need also to take over the latest changes of Gifford47 to the Dev branch.

**Comment by Tysonpower** [comment]
@14yannick where you able to test your latest changes? Otherwise i will do that tomorrow

**Comment by 14yannick** [comment]
I run this code since a couple days no without errors. The only issue I still have is that preasure and proximity threshold are not displayed in Web Ui. They are provided in the webservice but not displayed in the UI.
Would be good to check if it stil work with a DHT22 or DS18X20 as I have chaned something in the setup routine. @jkaberg could you try this repo if your dht22 still work?

**Comment by Tysonpower** [comment]
I moved the Pin config etc. to a new expert config section to make it more useable.

@14yannick What are the fields under sysinfo for? Are they also saved when a user clicks save?

**Comment by 14yannick** [comment]
I haven't noticed that the fields gets moved in this commit ba0de60d4a232917148d84ba0bbac77f3c697249 .
Yes as they are updated [here ](https://github.com/Gifford47/HCPBridgeMqtt/blob/d2ec3b95fe575eaec09e16b71ca7239ab29c6345/HCPBridgeESP32/src/preferencesKeys.h#L249 )when the form get submitted they need to be included as otherwise the preferences will be stored with empty value.
I also had the idea to split the configuration in multiple form. Important is then we have also to adjust the method called by the from submit or to send all fields in the submit als otherway they get saved with empty value.

**Comment by Tysonpower** [comment]
Should i move the fields under sysinfo somewhere else? Maybe under the expert Config section as well?

I just submit all fields currently at any time, so there should be no empty values.

After my Commit d2ec3b9 it looks like this btw.:

image

image

**Comment by 14yannick** [comment]
Nice yes add it to the expert tab and please also remove the read only attribute.

**Comment by Tysonpower** [comment]
> Nice yes add it to the expert tab and please also remove the read only attribute.

does it even make sense that these values are text fields? They can't be written correct? Because these are sensor values etc. maybe they are placed correctly down there but they should be text and not user input elements?

**Comment by Tysonpower** [comment]
nevermind, we need the fields all good, will change it as you mentioned

**Comment by 14yannick** [comment]
Maybe the first Idea was to display in the tab sysinfo the value returnded by the [sysinfo ](https://github.com/Gifford47/HCPBridgeMqtt/blob/cf0b5095b808151ecc573ba843fe82b7980855cf/HCPBridgeESP32/src/main.cpp#L755) get. But I think we could implement this on the next interation.

**Comment by Tysonpower** [comment]
also tested the Reset, works great! Nice work :) I think we can merge everything to the main dev or master repo soon.

I will make a new getting started instruction so people that use my preflashed PCBs also know how everything now works.

**Comment by Tysonpower** [comment]
updated the configuration text in the other branch: https://github.com/Gifford47/HCPBridgeMqtt/tree/docs_update

**Comment by 14yannick** [comment]
we just need to fix the form submission as not all values get send it will brick the esp needing a erase_flash.
image
@Tysonpower can you easily concatenate both form on submission in the JS of web UI? In a second time I will adjust the methode that only non empty strings get's interpreted and update preferences.

**Comment by Tysonpower** [comment]
> we just need to fix the form submission as not all values get send it will brick the esp needing a erase_flash. image @Tysonpower can you easily concatenate both form on submission in the JS of web UI? In a second time I will adjust the method that only non empty strings get's interpreted and update preferences.

okay will try to work on that tomorrow

**Comment by Tysonpower** [comment]
couldn't sleep before having a look haha, added a check to the save preferences so basic or expert conf are saved.

**Comment by 14yannick** [comment]
I think we are ready to merge it to dev branch.

**Comment by Gifford47** [comment]
> Nice yes add it to the expert tab and please also remove the read only attribute.

@14yannick Why would you like to remove the readonly flag? as Tysonpower said, i added it because they are only sensor values and shouldn´t confuse the user by editing it. my expectation is, that all values in the sysinfo tab should be readonly...

**Comment by Tysonpower** [comment]
> > Nice yes add it to the expert tab and please also remove the read only attribute.
> 
> @14yannick Why would you like to remove the readonly flag? as Tysonpower said, i added it because they are only sensor values and shouldn´t confuse the user by editing it. my expectation is, that all values in the sysinfo tab should be readonly...

yes, i expected that as well, but this is the content of the fields, so it's the mqtt name/text of the sensors, not the real value as it seems:

image

**Comment by Gifford47** [comment]
ok, now i understand :)
btw we should move all stuff (sensor query interval, thresholds, ...) after the [last pin definition](https://github.com/Gifford47/HCPBridgeMqtt/blob/3483fbebd8a3f8852f3381a4bed45f6a5203f31a/WebUI/webpage/index.html#L241C3-L241C6) into the other section.

i will add missing sensor values to the status api response so that we can integrate these values to the sys info tab.

**Comment by Tysonpower** [comment]
> ok, now i understand :) btw we should move all stuff (sensor query interval, thresholds, ...) after the [last pin definition](https://github.com/Gifford47/HCPBridgeMqtt/blob/3483fbebd8a3f8852f3381a4bed45f6a5203f31a/WebUI/webpage/index.html#L241C3-L241C6) into the other section.
> 
> i will add missing sensor values to the status api response so that we can integrate these values to the sys info tab.

Already did move them :)

https://github.com/Gifford47/HCPBridgeMqtt/pull/39#issuecomment-1718903710

**Comment by Gifford47** [comment]
they still stand under section "pin definition" but i meant "other" section :)

**Comment by Tysonpower** [comment]
yeah i was blind haha, moved them now

**Comment by Gifford47** [comment]
I've tested the current version with my new board and it's works great until now! Thanks for your work guys! :)

Btw some things needs to be more informational:
- short description/clearer labels of all input fields, what is it used for?
- units of the r/w fields are missing

**Comment by Tysonpower** [comment]
I changed the Ap logic to the following to make it simpler to use after users reported problems:

- IF the AP enable is checked it is enabled, also if a SSID is set
- IF the Wifi SSID is set -> Try to connect to WIFi as well

I also fixed the config Ui a bit so the text fields make more sense as wanted by @Gifford47  :)

**Comment by Tysonpower** [comment]
I think with this we can merge it into master btw.

**Comment by Tysonpower** [comment]
If there is no VETO i will merge the changes to master tomorrow, many people that use my PCBs reported no issues with this branch, so it should be fine, my own PCB included. @14yannick @Gifford47 @kfroeschl

**Review by kfroeschl — APPROVED** [review]
I only had a quick look but it looks good from my perspective.

**Comment by 14yannick** [comment]
Ok for me

**Comment by Gifford47** [comment]
Looks also fine for me. Thanks @all!

**Comment by Tysonpower** [comment]
great please someone of you approve #46 so we can sync all to master, thanks :)

**Pull request merged**
