### PR TITLE
Added Support for ESP32S3 and Flashing Instructions

### PR DESCRIPTION
**Pull request by Tysonpower**
Hi, added support for my ESP32 based Boards, also added a short instruction how the firmware needs ti be flashed because some Users asked me that.

### CODE REVIEW

**Comment by Gifford47** [comment]
could we change ```#define DEVICE_ID "garage_door"``` to     ```const char DEVICE_ID [] = "garage_door;"``` and concat it later with "BASE_FTOPIC" in the define?

**Comment by Tysonpower** [comment]
> could we change `#define DEVICE_ID "garage_door"` to `const char DEVICE_ID [] = "garage_door;"` and concat it later with "BASE_FTOPIC" in the define?

So you want to add a dynamic base topic? 'm not sure if you can concat a define with a const, two defines can be concatted tho.

**Comment by Tysonpower** [comment]
@Gifford47 you removed the ini entry for the esp32s3 i made, how do i select the idf target without it?

**Comment by Gifford47** [comment]
As I read in the docs, it's done by the board definition like [here](https://docs.platformio.org/en/stable/boards/espressif32/adafruit_feather_esp32s3_nopsram.html#board-espressif32-adafruit-feather-esp32s3-nopsram).

**Comment by Tysonpower** [comment]
exactly, it needs to be written inside the platformIO.ini file, that what i had in my pull request.

Should i add this back to the ini and make another PR? Without this there is no way to flash the boards with an ESP32S3.

I don't want that a user needs to change the platformio.ini if he has a s3 board.

If you have a better idea let me know.

```;ESP32-S3 based Boards - rename to env to activate or select esp32s3 project task
[env:esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino
board_build.f_cpu = 240000000L
board_build.f_flash = 40000000L
board_build.flash_mode = qio
monitor_speed = 9600
monitor_filters = esp32_exception_decoder
lib_ldf_mode = deep+
lib_deps = 
	esphome/ESPAsyncWebServer-esphome
	milesburton/DallasTemperature
	adafruit/Adafruit BME280 Library
	bblanchon/ArduinoJson
	plerup/EspSoftwareSerial
	ayushsharma82/AsyncElegantOTA
	ottowinter/AsyncMqttClient-esphome
	paulstoffregen/OneWire
	https://github.com/emelianov/modbus-esp8266
build_flags = 
	-D USE_ESP32S3
;	-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
;	-D DEBUG```

**Comment by Gifford47** [comment]
Ok, that was a misunderstanding. As I read it, it is sufficient if the S3 board definition is specified. This is also what I took from you. This sets the idf target. Can you test this once please?

If that should not be correct, we can change that gladly again. But then we only need the board and the build flags.
The rest is applied by the default env environment.

**Comment by Tysonpower** [comment]
Okay, did some tests, we need another env but you are right, it can be a lot smaller. Please add this to the platformio.ini file, thanks :)
```
[env:esp32s3_tynet]
board = adafruit_feather_esp32s3
board_build.f_flash = 40000000L
```

**Pull request merged**
